name: CI

on:
  push:
    paths:
      - 'Formula/*.rb'

jobs:
  install_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew update
      - name: Install formulae
        run: brew install --build-bottle --verbose --debug Formula/*.rb
      - name: Test formulae
        run: brew test Formula/*.rb
